AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Application 
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x 
      CodeUri: ./
      Events:
        ProfileApi:
          Type: Api
          Properties:
            Path: /Profile
            Method: GET